/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import biometricsystem.Constants;
import biometricsystem.Character;
import biometricsystem.DBFunction;
import biometricsystem.Digraph;
import biometricsystem.DigraphBehave;
import biometricsystem.User;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Anuradha
 */


public class SignUpForm extends javax.swing.JFrame {
    private static int attemptno=1;
    private int phrasecount=0;
    private int phrasecount2=0;
    private User user=null;
    private ArrayList<Character> phraseCharacters = null;
    //private static ArrayList<ArrayList<String>> PressingTimes=new ArrayList<ArrayList<String>>();
    //private static ArrayList<ArrayList<String>> ReleasingTimes=new ArrayList<ArrayList<String>>();
    //private static ArrayList<ArrayList<String>> intertimes=new ArrayList<ArrayList<String>>();
    private static ArrayList<ArrayList<Digraph>> PhraseLearningData= new ArrayList<ArrayList<Digraph>>();
    /**
     * Creates new form SignUpForm
     */
    public SignUpForm(User user) {
        this.user=user;
        phraseCharacters=new ArrayList<Character>();
        initComponents();
        jButton1.setEnabled(false);
        jLabel7.setText(Integer.toString(attemptno));
        jLabel5.setText("'"+Constants.PHRASE+"'");
        if(attemptno==Constants.TRIALS){
            jButton2.setEnabled(false);
            jButton1.setEnabled(true);
        }
        attemptno++;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("SignUp Form");

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Please type the phrase inside quotes as it is in the blank area and press \"Next\". There are 5 attempts");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Phrase:");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Attempt:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Traning Trial to learn key stroke pattern");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(60, 60, 60)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        char Char = evt.getKeyChar();
        if(evt.getKeyCode()==8 ||evt.getKeyCode()==46){
            retry("Backspace and Delete keys are not allowed.Invalid key stroke:(\nTake your same trial");
            return;
        }
        else if(evt.getKeyCode()==KeyEvent.VK_ENTER && attemptno<=Constants.TRIALS ){
            //jbutton2acctionperformed
           if(validatephrase()){
           PhraseLearningData.add(DigraphBehave.createDigraphs(Constants.PHRASE, phraseCharacters));

            this.setVisible(false);
            dispose();
        }
        if (attemptno <= Constants.TRIALS){
             this.display();
        }
							
        else{
            retry("Please enter the correct phrase");
        }
        }
        else if(evt.getKeyCode()==KeyEvent.VK_ENTER && attemptno==Constants.TRIALS+1){
            //register button action
            if(validatephrase()){
           PhraseLearningData.add(DigraphBehave.createDigraphs(Constants.PHRASE, phraseCharacters));
           ArrayList meantimeArray = DigraphBehave.constructMeanList(PhraseLearningData);
            for(int j = 0 ; j <meantimeArray.size(); j++){
		System.out.println(meantimeArray.get(j));
            }
            try {
                //add phraselearning data to db
                DBFunction.insertUser(user);
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SignUpForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(SignUpForm.class.getName()).log(Level.SEVERE, null, ex);
            }
           JOptionPane.showMessageDialog(null, "Your training session is completed successfully.");
           this.setVisible(false);
           dispose();
           new LandingForm().display();
        }
							
        else{
            retry("Please enter the correct phrase");
        }
            System.out.println("\nperform reg");
        }
        else if(phrasecount<Constants.PHRASE.length()){
            if(Char==Constants.PHRASE.charAt(phrasecount)){
                Character chr=new Character(Char);
                chr.setPressedTime(evt.getWhen());
                System.out.println(Char + "  press " + evt.getWhen());
                //add to array
                phraseCharacters.add(chr);
                
		phrasecount++;
            }
            else{
                retry("A wrong key stroke is typed.Try again");
                return;
                
            }
        }
        
        else{
            retry("A wrong phrase.Try again");
            return;
            
        }
     
        
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        char Char = evt.getKeyChar();
        if(Char== Constants.PHRASE.charAt(phrasecount2))
	{
            //add to th array
            phraseCharacters.get(phrasecount2).setReleasedTime(evt.getWhen());
            System.out.println(Char + " release " + evt.getWhen());
            phrasecount2++;
				
	}
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(validatephrase()){
           PhraseLearningData.add(DigraphBehave.createDigraphs(Constants.PHRASE, phraseCharacters));
            ArrayList meantimeArray = DigraphBehave.constructMeanList(PhraseLearningData);
            for(int j = 0 ; j <meantimeArray.size(); j++){
		System.out.println(meantimeArray.get(j));
            }
            try {
                //add phraselearning data to db
                DBFunction.insertUser(user);
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SignUpForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(SignUpForm.class.getName()).log(Level.SEVERE, null, ex);
            }
           JOptionPane.showMessageDialog(null, "Your training session is completed successfully.");
           this.setVisible(false);
           dispose();
           new LandingForm().display();
        }
							
        else{
            retry("Please enter the correct phrase");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(validatephrase()){
           PhraseLearningData.add(DigraphBehave.createDigraphs(Constants.PHRASE, phraseCharacters));

            this.setVisible(false);
            dispose();
        }
        if (attemptno <= Constants.TRIALS){
             this.display();
        }
							
        else{
            retry("Please enter the correct phrase");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    private void retry(String message){
	JOptionPane.showConfirmDialog(null,
		message, "Error",
		JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
	setVisible(false);
	dispose();
	attemptno--;
	this.display();
	}
    public boolean validatephrase(){
        if (jTextField2.getText()==null||
                jTextField2.getText().trim().length()==0||
                (!jTextField2.getText().equals(Constants.PHRASE))){
            return false;
        }
        else{
        return true;}
       
    }
    /**
     * @param args the command line arguments
     */
    public void display() {
        /* Set the Nimbus look and feel */
        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm(user).setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
